"""
Django settings for airguard project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).casefold() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY in .env before starting Django.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [item.strip() for item in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if item.strip()]
CSRF_TRUSTED_ORIGINS = [item.strip() for item in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if item.strip()]
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'airguard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'airguard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {'default': dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=60)}
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
elif os.environ.get('PGHOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['PGDATABASE'],
            'USER': os.environ['PGUSER'],
            'PASSWORD': os.environ['PGPASSWORD'],
            'HOST': os.environ['PGHOST'],
            'PORT': os.environ.get('PGPORT', '5432'),
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('DJANGO_DATABASE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'var' / 'static'
DATA_ROOT = Path(os.environ.get('AIRGUARD_DATA_DIR', BASE_DIR / 'var'))
MEDIA_ROOT = DATA_ROOT / 'media'
MEDIA_URL = 'media/'
if not DEBUG:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }

DEFAULT_SITE_URL = f'https://{RENDER_EXTERNAL_HOSTNAME}' if RENDER_EXTERNAL_HOSTNAME else 'http://127.0.0.1:8000'
AIRGUARD_SITE_URL = os.environ.get('AIRGUARD_SITE_URL', DEFAULT_SITE_URL)
AIRGUARD_UPLOAD_URL = os.environ.get('AIRGUARD_UPLOAD_URL', f'{AIRGUARD_SITE_URL.rstrip("/")}/api/v1/measurements/govee/')
AIRGUARD_INGEST_TOKEN = os.environ.get('AIRGUARD_INGEST_TOKEN', '')
AIRGUARD_POSTMARK_WEBHOOK_TOKEN = os.environ.get('AIRGUARD_POSTMARK_WEBHOOK_TOKEN', '')
AIRGUARD_MAX_UPLOAD_BYTES = int(os.environ.get('AIRGUARD_MAX_UPLOAD_BYTES', 20 * 1024 * 1024))
AIRGUARD_MAX_PM25 = float(os.environ.get('AIRGUARD_MAX_PM25', 2000))
AIRGUARD_MAX_FUTURE_MINUTES = int(os.environ.get('AIRGUARD_MAX_FUTURE_MINUTES', 10))
AIRGUARD_STALE_AFTER_MINUTES = int(os.environ.get('AIRGUARD_STALE_AFTER_MINUTES', 90))
AIRGUARD_FORECAST_MAX_AGE_HOURS = int(os.environ.get('AIRGUARD_FORECAST_MAX_AGE_HOURS', 12))
AIRGUARD_ALERT_COOLDOWN_HOURS = int(os.environ.get('AIRGUARD_ALERT_COOLDOWN_HOURS', 24))
AIRGUARD_SIGNUP_LIMIT_PER_HOUR = int(os.environ.get('AIRGUARD_SIGNUP_LIMIT_PER_HOUR', 20))
AIRGUARD_EMAIL_MAX_ATTEMPTS = int(os.environ.get('AIRGUARD_EMAIL_MAX_ATTEMPTS', 8))
AIRGUARD_VERIFY_MAX_AGE_HOURS = int(os.environ.get('AIRGUARD_VERIFY_MAX_AGE_HOURS', 48))
AIRGUARD_WEATHER_URL = os.environ.get('AIRGUARD_WEATHER_URL', 'https://api.open-meteo.com/v1/forecast')
AIRGUARD_WEATHER_LATITUDE = os.environ.get('AIRGUARD_WEATHER_LATITUDE', '41.6881')
AIRGUARD_WEATHER_LONGITUDE = os.environ.get('AIRGUARD_WEATHER_LONGITUDE', '-86.2355')
AIRGUARD_WEATHER_TIMEOUT_SECONDS = int(os.environ.get('AIRGUARD_WEATHER_TIMEOUT_SECONDS', 15))

GOVEE_IMAP_HOST = os.environ.get('GOVEE_IMAP_HOST', '')
GOVEE_IMAP_PORT = int(os.environ.get('GOVEE_IMAP_PORT', 993))
GOVEE_IMAP_TIMEOUT_SECONDS = int(os.environ.get('GOVEE_IMAP_TIMEOUT_SECONDS', 30))
GOVEE_IMAP_USER = os.environ.get('GOVEE_IMAP_USER', '')
GOVEE_IMAP_PASSWORD = os.environ.get('GOVEE_IMAP_PASSWORD', '')
GOVEE_IMAP_FOLDER = os.environ.get('GOVEE_IMAP_FOLDER', 'INBOX')
GOVEE_MAIL_ALLOWED_SENDER = os.environ.get('GOVEE_MAIL_ALLOWED_SENDER', '')
GOVEE_SOURCE_TIMEZONE = os.environ.get('GOVEE_SOURCE_TIMEZONE', '')

EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AirGuard Alerts <alerts@localhost>')
LOGIN_URL = '/admin/login/'

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', 31536000 if not DEBUG else 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
