# Generated by Django 5.2.16 on 2026-07-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='building-2', max_length=32)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('placement', models.CharField(choices=[('gym', 'Gym'), ('hallway', 'Hallway'), ('entrance', 'Entrance')], max_length=16)),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='dashboard.building')),
            ],
            options={
                'ordering': ('building', 'placement'),
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('pm25', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.sensor')),
            ],
            options={
                'ordering': ('observed_at',),
                'constraints': [models.UniqueConstraint(fields=('sensor', 'observed_at'), name='unique_sensor_reading')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_at', models.DateTimeField()),
                ('pm25', models.FloatField()),
                ('temperature', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=16)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='dashboard.sensor')),
            ],
            options={
                'ordering': ('forecast_at',),
                'constraints': [models.UniqueConstraint(fields=('sensor', 'forecast_at'), name='unique_sensor_forecast')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('threshold', models.PositiveSmallIntegerField(choices=[(51, 'Moderate or above'), (101, 'Unhealthy for sensitive groups or above'), (151, 'Unhealthy or above')])),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2)),
                ('audience', models.CharField(choices=[('community', 'Community'), ('facility', 'Facility manager')], default='community', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dashboard.building')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'building', 'audience'), name='unique_subscription')],
            },
        ),
    ]
